name: Build and Test Qt Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev

    - name: Install Qt5/Qt6 (yaqti)
      uses: WillBrennan/yaqti@2021.07.29
      with:
        version: '5.15.2'
        os: 'linux'
        platform: 'desktop'
        modules: 'qtcharts, qtnetworkauth'

    - name: Build with qmake and make
      run: |
        qmake
        make

    - name: Run tests
      run: |
        echo "No tests to run for this example"
