name: Build and Test Qt Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: supermarin/qt-action@v2
      with:
        qt-version: '5.15'
        qmake-args: 'CONFIG+=c++11'

    - name: Build with qmake and make
      run: |
        qmake
        make

    - name: Run tests
      run: |
        echo "No tests to run for this example"
